# These are supported funding model platforms

# github: [username]
# patreon: username
# open_collective: project-name
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# custom: ["https://www.paypal.me/username", "https://buy.me/coffee/username"]

# You can uncomment and customize these when you're ready to accept sponsorships
